// packages/react/src/components/SizeControlPanel.tsx
/**
 * @ldesign/size-react - SizeControlPanel Component
 * 
 * React component for size control panel
 */

import React from 'react'
import { useSizeConfig } from '../hooks/useSizeConfig'
import { useSizePresets } from '../hooks/useSizePresets'

/**
 * SizeControlPanel Props
 */
export interface SizeControlPanelProps {
  /**
   * Custom className
   */
  className?: string

  /**
   * Custom style
   */
  style?: React.CSSProperties

  /**
   * Show base size slider
   * @default true
   */
  showSlider?: boolean

  /**
   * Show preset buttons
   * @default true
   */
  showPresets?: boolean

  /**
   * Title text
   */
  title?: string
}

/**
 * SizeControlPanel Component
 * 
 * 尺寸控制面板组件，提供完整的尺寸管理界面
 * 
 * @example
 * ```tsx
 * <SizeControlPanel
 *   title="尺寸设置"
 *   showSlider={true}
 *   showPresets={true}
 * />
 * ```
 */
export function SizeControlPanel({
  className,
  style,
  showSlider = true,
  showPresets = true,
  title = '尺寸设置'
}: SizeControlPanelProps) {
  const { config, setBaseSize } = useSizeConfig()
  const { currentPreset, presets, applyPreset } = useSizePresets()

  return (
    <div
      className={className}
      style={{
        padding: '1rem',
        border: '1px solid #e0e0e0',
        borderRadius: '8px',
        backgroundColor: 'white',
        ...style
      }}
    >
      {/* Title */}
      {title && (
        <h3
          style={{
            margin: '0 0 1rem 0',
            fontSize: '1.125rem',
            fontWeight: 600,
            color: '#333'
          }}
        >
          {title}
        </h3>
      )}

      {/* Preset Buttons */}
      {showPresets && (
        <div style={{ marginBottom: showSlider ? '1.5rem' : 0 }}>
          <label
            style={{
              display: 'block',
              marginBottom: '0.5rem',
              fontSize: '0.875rem',
              fontWeight: 500,
              color: '#666'
            }}
          >
            预设尺寸
          </label>
          <div
            style={{
              display: 'flex',
              gap: '0.5rem',
              flexWrap: 'wrap'
            }}
          >
            {presets.map((preset) => {
              const isActive = preset.name === currentPreset

              return (
                <button
                  key={preset.name}
                  onClick={() => applyPreset(preset.name)}
                  style={{
                    padding: '0.5rem 1rem',
                    border: isActive ? '2px solid #0066ff' : '1px solid #ddd',
                    borderRadius: '6px',
                    background: isActive ? '#e6f2ff' : 'white',
                    color: isActive ? '#0066ff' : '#333',
                    cursor: 'pointer',
                    fontSize: '0.875rem',
                    fontWeight: isActive ? 600 : 400,
                    transition: 'all 0.2s ease'
                  }}
                >
                  {preset.label}
                  {preset.description && (
                    <span
                      style={{
                        display: 'block',
                        fontSize: '0.75rem',
                        opacity: 0.7,
                        marginTop: '0.125rem'
                      }}
                    >
                      {preset.baseSize}px
                    </span>
                  )}
                </button>
              )
            })}
          </div>
        </div>
      )}

      {/* Base Size Slider */}
      {showSlider && (
        <div>
          <label
            style={{
              display: 'block',
              marginBottom: '0.5rem',
              fontSize: '0.875rem',
              fontWeight: 500,
              color: '#666'
            }}
          >
            基础尺寸: {config.baseSize}px
          </label>
          <input
            type="range"
            min="12"
            max="20"
            step="1"
            value={config.baseSize}
            onChange={(e) => setBaseSize(Number(e.target.value))}
            style={{
              width: '100%',
              height: '6px',
              borderRadius: '3px',
              outline: 'none',
              background: 'linear-gradient(to right, #0066ff, #0066ff) no-repeat #ddd',
              backgroundSize: `${((config.baseSize - 12) / (20 - 12)) * 100}% 100%`
            }}
          />
          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              marginTop: '0.25rem',
              fontSize: '0.75rem',
              color: '#999'
            }}
          >
            <span>12px</span>
            <span>20px</span>
          </div>
        </div>
      )}
    </div>
  )
}

SizeControlPanel.displayName = 'SizeControlPanel'

// packages/solid/src/components/SizeControlPanel.tsx
/**
 * @ldesign/size-solid - SizeControlPanel Component
 * 
 * Advanced size control panel with preset selector and base size slider
 */

import { For, type JSX } from 'solid-js'
import { useSize } from '../hooks/useSize'

/**
 * SizeControlPanel Props
 */
export interface SizeControlPanelProps {
  /**
   * Custom className
   */
  class?: string

  /**
   * Custom style
   */
  style?: JSX.CSSProperties | string

  /**
   * Show base size slider
   * @default true
   */
  showSlider?: boolean

  /**
   * Minimum base size
   * @default 10
   */
  minSize?: number

  /**
   * Maximum base size
   * @default 24
   */
  maxSize?: number

  /**
   * Callback when size changes
   */
  onChange?: (config: { preset: string; baseSize: number }) => void
}

/**
 * SizeControlPanel Component
 * 
 * 高级尺寸控制面板
 * 
 * @example
 * ```tsx
 * <SizeControlPanel
 *   showSlider={true}
 *   minSize={12}
 *   maxSize={20}
 *   onChange={(config) => console.log('Config:', config)}
 * />
 * ```
 */
export function SizeControlPanel(props: SizeControlPanelProps) {
  const { config, currentPreset, presets, applyPreset, setBaseSize } = useSize()

  const showSlider = props.showSlider !== false
  const minSize = props.minSize || 10
  const maxSize = props.maxSize || 24

  const handlePresetChange = (presetName: string) => {
    applyPreset(presetName)
    props.onChange?.({
      preset: presetName,
      baseSize: config().baseSize
    })
  }

  const handleSizeChange = (size: number) => {
    setBaseSize(size)
    props.onChange?.({
      preset: currentPreset(),
      baseSize: size
    })
  }

  const panelStyle: JSX.CSSProperties = {
    padding: '1.5rem',
    border: '1px solid #e0e0e0',
    'border-radius': '8px',
    background: 'white',
    ...(typeof props.style === 'object' ? props.style : {})
  }

  const sectionStyle: JSX.CSSProperties = {
    'margin-bottom': '1.5rem'
  }

  const labelStyle: JSX.CSSProperties = {
    display: 'block',
    'margin-bottom': '0.5rem',
    'font-weight': 600,
    color: '#333'
  }

  const presetGridStyle: JSX.CSSProperties = {
    display: 'grid',
    'grid-template-columns': 'repeat(auto-fit, minmax(100px, 1fr))',
    gap: '0.5rem'
  }

  const presetButtonStyle = (isActive: boolean): JSX.CSSProperties => ({
    padding: '0.75rem 1rem',
    border: `2px solid ${isActive ? '#0066ff' : '#e0e0e0'}`,
    'border-radius': '6px',
    background: isActive ? '#0066ff' : 'white',
    color: isActive ? 'white' : '#333',
    cursor: 'pointer',
    'font-weight': isActive ? 600 : 400,
    transition: 'all 0.2s ease',
    'text-align': 'center'
  })

  const sliderContainerStyle: JSX.CSSProperties = {
    display: 'flex',
    'align-items': 'center',
    gap: '1rem'
  }

  const sliderStyle: JSX.CSSProperties = {
    flex: 1,
    height: '6px',
    'border-radius': '3px'
  }

  const valueDisplayStyle: JSX.CSSProperties = {
    'min-width': '50px',
    'text-align': 'right',
    'font-weight': 600,
    color: '#0066ff'
  }

  return (
    <div class={props.class} style={panelStyle}>
      {/* Preset Selector */}
      <div style={sectionStyle}>
        <label style={labelStyle}>
          预设尺寸
        </label>
        <div style={presetGridStyle}>
          <For each={presets()}>
            {(preset) => {
              const isActive = () => preset.name === currentPreset()

              return (
                <button
                  onClick={() => handlePresetChange(preset.name)}
                  style={presetButtonStyle(isActive())}
                >
                  <div>{preset.label}</div>
                  <div style={{ 'font-size': '0.75rem', opacity: 0.8 }}>
                    {preset.baseSize}px
                  </div>
                </button>
              )
            }}
          </For>
        </div>
      </div>

      {/* Base Size Slider */}
      {showSlider && (
        <div style={{ 'margin-bottom': 0 }}>
          <label style={labelStyle}>
            基础尺寸
          </label>
          <div style={sliderContainerStyle}>
            <input
              type="range"
              min={minSize}
              max={maxSize}
              value={config().baseSize}
              onInput={(e) => handleSizeChange(Number(e.currentTarget.value))}
              style={sliderStyle}
            />
            <span style={valueDisplayStyle}>
              {config().baseSize}px
            </span>
          </div>
        </div>
      )}
    </div>
  )
}
